environment   = "prod"
aws_region    = "eu-west-3"
project_name  = "todo-app"
instance_type = "t3.medium"
key_name      = "todo-app"
ssh_cidr      = "0.0.0.0/0"
# domain_name       = "todo-app.example.com"
# route53_zone_id   = "ZXXXXXXXXXXXXXXXXXX"